// PLAYWRIGHT_MODULE can point to the bundled Playwright installation.
import assert from 'node:assert/strict';
import { mkdtemp, cp, rm, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import net from 'node:net';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const dir = await mkdtemp(path.join(tmpdir(), 'cinematic-browser-'));
const reservation = net.createServer(); await new Promise((resolve) => reservation.listen(0, '127.0.0.1', resolve));
const port = reservation.address().port; await new Promise((resolve) => reservation.close(resolve));
let server, browser; const errors = [];
try {
  for (const name of ['src', 'public', 'agents-film', 'package.json']) await cp(path.join(root, name), path.join(dir, name), { recursive: true });
  await symlink(path.join(root, 'node_modules'), path.join(dir, 'node_modules'));
  server = spawn(process.execPath, ['src/server.js'], { cwd: dir, env: { ...process.env, PORT: String(port), MOCK: '1', OPENROUTER_API_KEY: '', WAVESPEED_API_KEY: '' }, stdio: ['ignore', 'pipe', 'pipe'] });
  const base = `http://127.0.0.1:${port}`;
  for (let i = 0; i < 100; i++) { try { if ((await fetch(`${base}/api/config`)).ok) break; } catch {} await new Promise((r) => setTimeout(r, 50)); }
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.on('pageerror', (e) => errors.push(e.message));
  await page.addInitScript(() => { localStorage.setItem('raw-mic', '0'); localStorage.setItem('story-mic', '0'); localStorage.setItem('lab.motion.experiments.v1', JSON.stringify([{ id: 'sentinel', name: 'Motion history preserved', createdAt: '2026-10-09' }])); });
  await page.route('**/api/lab/models', (r) => r.fulfill({ json: { mock: true, models: [{ id: 'chosen/vision-llm', name: 'Chosen Vision LLM', prompt: 1, completion: 1 }], harness: { version: 'test', tools: { search: true } } } }));
  await page.goto(`${base}/#laboratorio`); await page.locator('#lab-home').waitFor({ state: 'visible' });
  await page.locator('#lab-home a[href="#laboratorio/cinematic-videos"]').click();
  await page.waitForFunction(() => document.getElementById('cinematic-catalog-status').textContent.includes('2 generadores de OpenRouter'));
  assert.equal(await page.locator('#lab-motion-folder').isVisible(), false);
  assert.equal(await page.locator('#cinematic-generators .cinematic-generator').count(), 2);
  await page.locator('#cinematic-llm').fill('chosen/vision-llm');
  await page.locator('#cinematic-message').fill('Un auto azul bajo la lluvia'); await page.locator('#cinematic-chat-send').click();
  await page.locator('#cinematic-chat .assistant').waitFor();
  await page.locator('#cinematic-finalize').click(); await page.waitForFunction(() => document.getElementById('cinematic-prompt').value.includes('cinematic slow push-in'));
  assert.equal(await page.locator('#cinematic-chat .cinematic-turn').count(), 4);
  await page.locator('#cinematic-images').setInputFiles({ name: 'reference.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64') });
  await page.locator('#cinematic-references img').waitFor();
  await page.locator('#cinematic-audio-file').setInputFiles({ name: 'reference.wav', mimeType: 'audio/wav', buffer: Buffer.from('UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAAAAA=', 'base64') });
  await page.locator('#cinematic-references audio').waitFor();
  await page.locator('#cinematic-add-generator').click(); await page.locator('#cinematic-add-generator').click();
  assert.equal(await page.locator('#cinematic-add-generator').isDisabled(), true);
  const gs = page.locator('#cinematic-generators .cinematic-generator');
  await gs.nth(2).locator('select').selectOption('openrouter'); await gs.nth(2).locator('input').fill('alibaba/wan-3.0-prime');
  await gs.nth(3).locator('input').fill('alibaba/wan-3.0-prime/reference-to-video');
  await page.locator('#cinematic-name').fill('Cinematic comparison test');
  await page.locator('#cinematic-mode-prompt').click();
  assert.equal(await page.locator('#cinematic-conversation').isVisible(), false);
  await page.locator('#cinematic-prompt').fill('Same cinematic prompt for every selected model.');
  await page.waitForFunction(() => document.getElementById('cinematic-preflight').textContent.includes('C · Se omitirá'));
  await page.locator('#view-lab .raw-scroll').evaluate((n) => { n.scrollTop = 0; });
  await page.screenshot({ path: '/tmp/cinematic-desktop.png', fullPage: true });
  await page.locator('#cinematic-run').click();
  await page.waitForFunction(() => document.querySelectorAll('#cinematic-results .lab-side[data-status="done"]').length === 3);
  assert.equal(await page.locator('#cinematic-results .lab-side[data-status="skipped"]').count(), 1);
  assert.equal(await page.locator('#cinematic-results .lab-side').count(), 4);
  assert.equal(await page.locator('#cinematic-prompt').isDisabled(), true);
  const a = page.locator('#cinematic-results [data-side="A"]');
  await a.getByRole('button', { name: '✓ Aprobar', exact: true }).click();
  await a.getByRole('button', { name: 'Calidad: 5 de 5', exact: true }).click();
  await a.getByRole('button', { name: 'Fidelidad: 4 de 5', exact: true }).click();
  await a.getByRole('textbox', { name: 'Opinión A' }).fill('Mejor luz y movimiento');
  await page.getByRole('button', { name: 'Prefiero A', exact: true }).click();
  await page.getByRole('textbox', { name: 'Conclusión del experimento' }).fill('A es el mejor');
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('lab.cinematic.experiments.v1'))[0]);
  assert.equal(saved.results[0].eval.quality, 5); assert.equal(saved.results[0].eval.fidelity, 4); assert.equal(saved.preference, 'A');
  assert.equal(saved.turns.length, 4); assert.equal(saved.prompt, 'Same cinematic prompt for every selected model.');
  await page.reload(); await page.locator('#cinematic-history-toggle').click(); await page.getByRole('button', { name: 'Abrir', exact: true }).click();
  await page.locator('#cinematic-results [data-side="A"]').waitFor();
  assert.equal(await page.getByRole('button', { name: 'Calidad: 5 de 5', exact: true }).first().getAttribute('aria-pressed'), 'true');
  assert.equal(await page.locator('#cinematic-references img').count(), 1); assert.equal(await page.locator('#cinematic-references audio').count(), 1);
  assert.equal(await page.locator('#cinematic-prompt').inputValue(), saved.prompt);
  await page.locator('#cinematic-history-toggle').click(); assert.ok(await page.locator('#cinematic-history').innerText().then((t) => t.includes('Calidad')));
  await page.locator('a[data-lab-folder="motion-design"]').click(); await page.locator('#lab-motion-folder').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#lab-cinematic-folder').isVisible(), false);
  assert.equal(await page.locator('#lab-experiment .lab-side').count(), 2);
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('lab.motion.experiments.v1'))[0].id), 'sentinel');
  await page.locator('.tab[data-tab="raw"]').click(); await page.locator('.tab[data-tab="lab"]').click(); await page.locator('#lab-home').waitFor({ state: 'visible' });
  await page.locator('a[data-lab-folder="cinematic-videos"]').click(); await page.locator('#cinematic-new').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '/tmp/cinematic-mobile.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.getElementById('lab-cinematic-folder').scrollWidth <= document.getElementById('lab-cinematic-folder').clientWidth + 1), 'no horizontal overflow on mobile');
  assert.deepEqual(errors, []);
  console.log('Cinematic browser: folders, conversation, references/audio, max four, skip, ratings, history/reload, motion isolation and mobile passed.');
} finally { await browser?.close(); server?.kill(); await rm(dir, { recursive: true, force: true }); }
